### ISSUE TITLE
403 error, app not assigned

### ISSUE THREAD

**Issue by TanJicong** [sassoftware/viya4-orders-cli#5]
Encounter the attached 403 error after login to sas api portal using SAS profile. As a result, not able to create the credentials to use SAS API. Not sure who to contact
![403 error](https://user-images.githubusercontent.com/48216678/101365909-4fa4e080-38df-11eb-8781-1b597fd31fba.jpg)

**Comment by sarahcpage** [comment]
IT took care of enabling Okta for non-SAS employees. Closing.
