### ISSUE TITLE
issue with building project 

### ISSUE THREAD

**Issue by esshab** [sassoftware/viya4-orders-cli#8]
[azureuser@mgt Viya4]$ docker build github.com/sassoftware/viya4-orders-cli -t viya4-orders-cli
unable to prepare context: unable to 'git clone' to temporary context directory: Error trying to use git: exit status 128 (Cloning into '/tmp/docker-build-git267569601'...
git: 'remote-https' is not a git command. See 'git --help'.
)

**Comment by sarahcpage** [comment]
Hi, what version of Git are you using? Is git-remote-https.exe present in your Git installation?

**Comment by esshab** [comment]
[azureuser@mgt ~]$ git --version
git version 2.30.0

also from this instruction where I get the 923456_lts_depassets.tgz?
What should I include the configuration file..the API and Scret?
Can you provide a sample yml configuration file?


Using a configuration file, /c/Users/auser/vocli/.viya4-orders-cli.yaml, to convey your API credentials, get deployment assets for SAS Viya order 923456 at the latest version of the Long Term Support (lts) cadence. Send the contents to file /c/Users/auser/vocli/sasfiles/923456_lts_depassets.tgz:

Regards,
Esmat Shabon
Sr. Solution Advisor
Fraud and Security Intelligence

Phone: ( 571) 499-1755
Esmat.shabon@sas.com<mailto:Esmat.shabon@sas.com>

**Comment by sarahcpage** [comment]
Is git-remote-https.exe present in your Git installation?
From the README.md on the project homepage in GitHub:
![image](https://user-images.githubusercontent.com/37630771/107255485-5ac2dc80-6a06-11eb-8b33-f4002df5b384.png)

**Comment by sarahcpage** [comment]
user had bad git installation - closing
